# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
stabit2Mat1 <- function(Cr, Cmatchr, Sr, Smatchr, Dr, dr, Mr, Hr, nCollegesr, nStudentsr, CCr, SSr, CCmatchr, SSmatchr, Lr, studentIdsr, collegeIdr, nEquilibsr, sopt2equr, equ2soptr, copt2equr, equ2coptr, coptidr, n, N, niter, T, thin, display_progress = TRUE) {
    .Call('matchingMarkets_stabit2Mat1', PACKAGE = 'matchingMarkets', Cr, Cmatchr, Sr, Smatchr, Dr, dr, Mr, Hr, nCollegesr, nStudentsr, CCr, SSr, CCmatchr, SSmatchr, Lr, studentIdsr, collegeIdr, nEquilibsr, sopt2equr, equ2soptr, copt2equr, equ2coptr, coptidr, n, N, niter, T, thin, display_progress)
}

#' @export
stabit2Sel1 <- function(Yr, Xmatchr, Cr, Cmatchr, Sr, Smatchr, Dr, dr, Mr, Hr, nCollegesr, nStudentsr, XXmatchr, CCr, SSr, CCmatchr, SSmatchr, Lr, studentIdsr, collegeIdr, nEquilibsr, sopt2equr, equ2soptr, copt2equr, equ2coptr, coptidr, n, N, binary, niter, T, censored, thin, display_progress = TRUE) {
    .Call('matchingMarkets_stabit2Sel1', PACKAGE = 'matchingMarkets', Yr, Xmatchr, Cr, Cmatchr, Sr, Smatchr, Dr, dr, Mr, Hr, nCollegesr, nStudentsr, XXmatchr, CCr, SSr, CCmatchr, SSmatchr, Lr, studentIdsr, collegeIdr, nEquilibsr, sopt2equr, equ2soptr, copt2equr, equ2coptr, coptidr, n, N, binary, niter, T, censored, thin, display_progress)
}

#' @export
stabit2Sel2 <- function(Yr, Xmatchr, Cr, Cmatchr, Dr, dr, Mr, Hr, nCollegesr, nStudentsr, XXmatchr, CCr, CCmatchr, Lr, studentIdsr, collegeIdr, n, N, binary, niter, T, censored, thin, display_progress = TRUE) {
    .Call('matchingMarkets_stabit2Sel2', PACKAGE = 'matchingMarkets', Yr, Xmatchr, Cr, Cmatchr, Dr, dr, Mr, Hr, nCollegesr, nStudentsr, XXmatchr, CCr, CCmatchr, Lr, studentIdsr, collegeIdr, n, N, binary, niter, T, censored, thin, display_progress)
}

#' @export
stabitSel2 <- function(Xr, Rr, Wr, One, Two, T, offOutr, offSelr, sigmabarbetainverse, sigmabaralphainverse, niter, n, l, Pr, p, binary, selection, censored, ntu, gPrior, display_progress = TRUE) {
    .Call('matchingMarkets_stabitSel2', PACKAGE = 'matchingMarkets', Xr, Rr, Wr, One, Two, T, offOutr, offSelr, sigmabarbetainverse, sigmabaralphainverse, niter, n, l, Pr, p, binary, selection, censored, ntu, gPrior, display_progress)
}

